on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install pio
        run: pip install -U platformio

      - name: Build
        run: python ./scripts/ci.py
